name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: menouerreg.azurecr.io
          username: menouerreg
          password: 6KmyKuRBSDqVBK5iVVfjAe/JoPmosyutM0CpzWMNuG+ACRD0e4tU
      - run: |
          docker build . -t menouerreg.azurecr.io/menouerreg:${{ github.sha }}
          docker push menouerreg.azurecr.io/menouerreg:${{ github.sha }}